# The AWS Serverless Application Model (SAM) CLI configuration file
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "tacocat-gallery-website-hosting-dev"

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "tacocat-gallery-website-hosting-prod"

[default.validate.parameters]
lint = true

[default.build.parameters]
cached = true
parallel = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[default.deploy.parameters]
s3_prefix = "tacocat-gallery-website-hosting/dev"
resolve_s3 = true
confirm_changeset = true
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "GalleryAppDomain=staging-pix.tacocat.com",
    "DomainCertificateArn=arn:aws:acm:us-east-1:010410881828:certificate/092ab57c-f87d-4c44-a72c-63cfbbb55800",
]

[prod.deploy.parameters]
s3_prefix = "tacocat-gallery-website-hosting/prod"
resolve_s3 = true
confirm_changeset = true
region = "us-east-1"
image_repositories = []
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "GalleryAppDomain=pix.tacocat.com",
    "DomainCertificateArn=arn:aws:acm:us-east-1:010410881828:certificate/e142cda0-96db-4651-92fd-35dd9a52e9a2",
]