# -----------------------------------------------------------------------------
# This is an AWS Serverless Application Model (SAM) template
# It defines the "stack" of AWS resources needed to run the SAM app
# -----------------------------------------------------------------------------
AWSTemplateFormatVersion: 2010-09-09

# -----------------------------------------------------------------------------
# This file is written in SAM syntax, and gets transfomed and expanded into a
# CloudFormation template.  The CloudFormation template is what actually gets
# deployed.  The main point is that SAM syntax is much simpler, with a lot less
# boilerplate around declaring resources like Lambda functions and their
# accompanying execution roles.
# -----------------------------------------------------------------------------
Transform: AWS::Serverless-2016-10-31

# -----------------------------------------------------------------------------
# This particular template defines website hosting for the Tacocat photo gallery
# -----------------------------------------------------------------------------
Description: Tacocat gallery static SPA website hosting

# -----------------------------------------------------------------------------
# Parameters that can be specified when deploying this stack
# -----------------------------------------------------------------------------
Parameters:
  GalleryAppDomain:
    Description: Domain of the Tacocat photo gallery web app 
    Type: String
    AllowedValues:
      - staging-pix.tacocat.com
      - pix.tacocat.com
  DomainCertificateArn:
    Description: ARN of the ACM certificate for the GalleryAppDomain domain
    Type: String
    AllowedValues:
      - arn:aws:acm:us-east-1:010410881828:certificate/092ab57c-f87d-4c44-a72c-63cfbbb55800 # staging-pix.tacocat.com
      - arn:aws:acm:us-east-1:010410881828:certificate/e142cda0-96db-4651-92fd-35dd9a52e9a2 # pix.tacocat.com

# -----------------------------------------------------------------------------
# Resources are the actual assets that will be provisioned on AWS
# -----------------------------------------------------------------------------
Resources:

  # -----------------------------------------------------------------------------
  # S3 bucket to host single page app (SPA) website
  # -----------------------------------------------------------------------------
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Delete Old Versions
            NoncurrentVersionExpirationInDays: 7 # delete old versions after a week
            ExpiredObjectDeleteMarker: true
            Status: Enabled
  
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Id: PolicyForCloudFrontPrivateContent
        Statement:
        - Sid: AllowCloudFrontServicePrincipal
          Effect: "Allow"
          Principal:
            Service: cloudfront.amazonaws.com
          Action: s3:GetObject
          Resource: !Sub arn:aws:s3:::${WebsiteBucket}/*
          Condition:
            StringEquals:
              "AWS:SourceArn": !Join [ "", [ "arn:aws:cloudfront::", !Ref "AWS::AccountId", ":distribution/", !Ref CloudFrontDistribution ] ]
  
  # -----------------------------------------------------------------------------
  # CloudFront Distribution for hosting the single page app website
  # -----------------------------------------------------------------------------
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub Static SPA website files for ${AWS::StackName}
        DefaultRootObject: index.html
        HttpVersion: http2
        Aliases:
        - !Ref GalleryAppDomain
        ViewerCertificate:
          AcmCertificateArn: !Ref DomainCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        # These custom error responses are needed to support single page apps
        # When a user requests a path that doesn't physically exist such as
        # /2001/12-31/, S3 will return a 404 (actually a 403).  This tells 
        # CloudFront to return index.html instead of that error.
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Origins:
        - Id: S3Origin
          DomainName: !GetAtt WebsiteBucket.RegionalDomainName
          OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
          S3OriginConfig: 
            OriginAccessIdentity: ""
        CacheBehaviors:
          - PathPattern: /_app/immutable/*
            TargetOriginId: S3Origin
            Compress: true
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: !Ref ImmutableCachePolicy
            ResponseHeadersPolicyId: !Ref ImmutableResponseHeadersPolicy
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized managed policy - use this if not using a custom ForwardedValues
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachedMethods:
          - GET
          - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${WebsiteBucket}-origin-access-control
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Set Cache-Control header to cache forever
  ImmutableResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties: 
      ResponseHeadersPolicyConfig: 
        Name: !Sub ImmutableResponseHeadersPolicy-${AWS::StackName}
        Comment: !Sub Immutable response headers policy for ${AWS::StackName}
        CustomHeadersConfig:
          Items:
            - Header: Cache-Control
              Value: public, max-age=31536000, immutable
              Override: true

  # Caching policy to cache forever
  ImmutableCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub ImmutableCachePolicy-${AWS::StackName}
        Comment: Cache for a year
        DefaultTTL: 31536000 # 1 year
        MaxTTL: 31536000 # 1 year
        MinTTL: 31536000 # 1 year
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none


# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------
Outputs:
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID for hosting web front end
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name for accessing web front end
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebS3BucketName:
    Description: S3 Bucket for hosting web site
    Value: !Ref WebsiteBucket
